### ISSUE TITLE
Cannot spread async value

### ISSUE THREAD

**Issue by Tvrqvoise** [rpetrich/babel-plugin-transform-async-to-promises#2]
The following code encounters an exception while compiling:

```js
const { foo } = await getStuff()
```

Changing the above to the following causes it to correctly compile and work:
```js
const stuff = await getStuff()
stuff.foo
```

```
Property init of VariableDeclarator expected node to be of a type ["Expression"] but instead got "ObjectPattern"
at Object.validate (./node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (./node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (./node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath.replaceWith (./node_modules/babel-traverse/lib/path/replacement.js:160:8)
    at extractDeclarations (./node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:766:21)
    at Object.rewriteAwaitPath (./node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:1371:102)
    at NodePath._call (./node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (./node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (./node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (./node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (./node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (./node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (./node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (./node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (./node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (./node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (./node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (./node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (./node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (./node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (./node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (./node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (./node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (./node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (./node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (./node_modules/babel-traverse/lib/context.js:108:19)
```

My .babelrc
```
{
  "presets": [
    ["env", { "modules": false }],
    "react",
    "stage-1"
  ],
  "plugins": [
    "babel-plugin-transform-async-to-promises",
    "transform-react-jsx",
    ["react-css-modules", {
      "filetypes": {
        ".less": {
          "syntax": "postcss-less"
        }
      },
      "context": "javascript"
    }],
  ]
}
```

**Comment by rpetrich** [comment]
Thanks for reporting. This specific case now works in the master branch. I'm not as familiar with spread syntax as I am JavaScript syntax that has been around longer. Do you have more test cases or samples I can integrate?

**Comment by Tvrqvoise** [comment]
Sure -- I think technically I was wrong to call it a spread, as it's actually a "destructure".  Here's a more complex example:

```js
async function getFooBar () {
  return {
    foo: {
      bar: 'baz'
    }
  }
}

async function () {
  const { foo: { bar } } = await getFooBar()
  return bar // 'baz'
}
```
