### ISSUE TITLE
ReferenceError: Container is falsy

### ISSUE THREAD

**Issue by marvinhagemeister** [rpetrich/babel-plugin-transform-async-to-promises#20]
Found this issue while working on a fix for https://github.com/developit/microbundle/issues/259 . The code is the transpiled output after TypeScript which adds its own helpers. The issue only seem to happen when there is an `await` keyword in both `try` and `finally` blocks.

Input code:

```js
import * as tslib_1 from "tslib";
export default async function foo() {
  var e_1, _a;
  const out = [];
  try {
    for (
      var _b = tslib_1.__asyncValues([1, 2]), _c;
      (_c = await _b.next()), !_c.done;

    ) {
      const item = _c.value;
      out.push(item);
    }
  } catch (e_1_1) {
    e_1 = { error: e_1_1 };
  } finally {
    try {
      if (_c && !_c.done && (_a = _b.return)) await _a.call(_b);
    } finally {
      if (e_1) throw e_1.error;
    }
  }
  return out;
}
foo().then(console.log);
```

Error:

```txt
ReferenceError: Container is falsy
    at NodePath._replaceWith (/myproject/node_modules/@babel/traverse/lib/path/replacement.js:188:11)
    at NodePath._remove (/myproject/node_modules/@babel/traverse/lib/path/removal.js:51:10)
    at NodePath.remove (/myproject/node_modules/@babel/traverse/lib/path/removal.js:30:8)
    at Object.VariableDeclaration (/myproject/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:896:45)
    at NodePath._call (/myproject/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/myproject/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/myproject/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/myproject/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/myproject/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/myproject/node_modules/@babel/traverse/lib/context.js:146:19)
```

**Comment by marvinhagemeister** [comment]
oh wait, the issue is rather that the variable `_b` is badly hoisted. Declaring it at the correct scope fixes it for me.

**Comment by marvinhagemeister** [comment]
Turns out that the badly hoisted `_b` declaration is a bug in TypeScript itself. Sorry for the noise!

**Comment by rpetrich** [comment]
Reopening since this plugin should be required to handle var scope correctly, and there’s a good test case hidden in TypeScript’s generated code.

**Comment by luwes** [comment]
I ran into the same issue today not using typescript

```js
  async function init() {
    const options = {};

    div = createElement('div');

    const mediaUrl = `https://cdn.jwplayer.com/v2/media/Fpw44kH6`;
    const response = await fetch(mediaUrl);
    const media = await response.json();
    const jwplayer = await loadScript(API_URL, API_GLOBAL);
    const config = {
      ...media,
      ...options
    };

    // jwplayer(div).setup(config);
  }
```
