### ISSUE TITLE
Error when binding a top-level async function

### ISSUE THREAD

**Issue by jimmydief** [rpetrich/babel-plugin-transform-async-to-promises#22]
Encountered an error while transforming some code that binds to a top-level async function.

Code:
```
async function handleError() {}

beforeAll(async () => {
	page.addListener('pageerror', handleError.bind(this));
});
```

Error:
```
TypeError: Cannot read property 'scope' of null
    at rewriteToNamedConstant (~/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:1053:24)
    at rewriteThisExpressions (~/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:1070:9)
    at PluginPass.ArrowFunctionExpression (~/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:2991:21)
    at newFn (~/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (~/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (~/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (~/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (~/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (~/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (~/node_modules/@babel/traverse/lib/context.js:144:19)
```

Heres' my Babel config:
```
{
	plugins: ['transform-async-to-promises']
}
```

And some version info:
`node`: 8.11.1
`@babel/core`: 7.3.3
`babel-plugin-transform-async-to-promises`: 0.8.4

**Comment by rpetrich** [comment]
Should be resolved in 0.8.5
