### ISSUE TITLE
TypeError: unknown: Cannot read property 'isVariableDeclaration' of undefined

### ISSUE THREAD

**Issue by Petah** [rpetrich/babel-plugin-transform-async-to-promises#51]
When trying to run the example I am getting this error:

    $ node compile-babel.js
    /project/node_modules/@babel/core/lib/transformation/index.js:58
        throw e;
        ^

    TypeError: unknown: Cannot read property 'isVariableDeclaration' of undefined
        at insertHelper (/project/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:2875:29)
        at helperReference (/project/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:3007:33)
        at PluginPass.FunctionExpression (/project/node_modules/babel-plugin-transform-async-to-promises/async-to-promises.js:3547:71)
        at newFn (/project/node_modules/@babel/traverse/lib/visitors.js:179:21)
        at NodePath._call (/project/node_modules/@babel/traverse/lib/path/context.js:55:20)
        at NodePath.call (/project/node_modules/@babel/traverse/lib/path/context.js:42:17)
        at NodePath.visit (/project/node_modules/@babel/traverse/lib/path/context.js:90:31)
        at TraversalContext.visitQueue (/project/node_modules/@babel/traverse/lib/context.js:112:16)
        at TraversalContext.visitSingle (/project/node_modules/@babel/traverse/lib/context.js:84:19)
        at TraversalContext.visit (/project/node_modules/@babel/traverse/lib/context.js:140:19) {
    code: 'BABEL_TRANSFORM_ERROR'
    }

Here is the script:

    const code = `
    async function fetchAsObjectURL(url) {
        const response = await fetch(url);
        const blob = await response.blob();
        return URL.createObjectURL(blob);
    }
    `;
    var babel = require('@babel/core');
    var result = babel.transform(code, {
        plugins: ['babel-plugin-transform-async-to-promises'],
    });
    process.stdout.write(result.code + '\n');

**Comment by kentcdodds** [comment]
I ran into this as well and you will find that if you add more to the code it goes away. For example:

```javascript
const code = `
async function fetchAsObjectURL(url) {
    const response = await fetch(url);
    const blob = await response.blob();
    return URL.createObjectURL(blob);
}
export default fetchAsObjectURL // <-- add that
// or you could do: fetchAsObjectURL('https://example.com/bla.json')
// just need to have *something*
`;
var babel = require('@babel/core');
var result = babel.transform(code, {
    plugins: ['babel-plugin-transform-async-to-promises'],
});
process.stdout.write(result.code + '\n');
```

I'm not really concerned about this because there's no real-world scenario where you wouldn't need to have additional lines of code in the file.
